name: Android Release (AAB)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Restore upload keystore from secret
        env:
          UPLOAD_KEYSTORE_BASE64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
        run: |
          echo "$UPLOAD_KEYSTORE_BASE64" | base64 -d > upload.keystore 2>/dev/null || echo "$UPLOAD_KEYSTORE_BASE64" | base64 --decode > upload.keystore
          ls -l upload.keystore

      - name: Gradle wrapper
        run: |
          [ -f ./gradlew ] && chmod +x gradlew || true
          ./gradlew --version || true
          if [ ! -f ./gradlew ]; then
            echo "No gradlew found. Initializing..."
            curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q /tmp/gradle.zip -d /tmp/gradle
            /tmp/gradle/gradle-8.7/bin/gradle wrapper
            chmod +x gradlew
          fi

      - name: Build AAB (bundleRelease)
        env:
          KEYSTORE_PATH: upload.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew --version
          ./gradlew clean bundleRelease --stacktrace --info --no-daemon

      - name: Build APK (assembleRelease)
        env:
          KEYSTORE_PATH: upload.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # 1) どのタスクがあるか先に一覧（見えない場合の保険）
          ./gradlew :app:tasks --all --no-daemon --info | sed -n '1,200p'

          # 2) 署名環境変数が「空でない」ことだけチェック（値は出さない）
          for v in KEYSTORE_PATH KEYSTORE_PASSWORD KEY_ALIAS KEY_PASSWORD; do
            if [ -z "${!v}" ]; then echo "::error title=Missing Secret::${v} is empty"; fi
          done

          # 3) 詳細ログをファイル採集して失敗原因を可視化
          mkdir -p build-logs
          ./gradlew :app:assembleRelease --stacktrace --info --warning-mode all --no-daemon \
            | tee build-logs/assembleRelease.log

      - name: Upload build logs
        if: always()  # 成否に関係なく採集
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-logs
          path: |
            build-logs/
            app/build/reports/
            app/build/outputs/logs/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
