name: Android Release (AAB)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Restore upload keystore from secret
        env:
          UPLOAD_KEYSTORE_BASE64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
        run: |
          echo "$UPLOAD_KEYSTORE_BASE64" | base64 -d > upload.keystore 2>/dev/null || echo "$UPLOAD_KEYSTORE_BASE64" | base64 --decode > upload.keystore
          ls -l upload.keystore

      - name: Gradle wrapper
        run: |
          [ -f ./gradlew ] && chmod +x gradlew || true
          ./gradlew --version || true
          if [ ! -f ./gradlew ]; then
            echo "No gradlew found. Initializing..."
            curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q /tmp/gradle.zip -d /tmp/gradle
            /tmp/gradle/gradle-8.7/bin/gradle wrapper
            chmod +x gradlew
          fi

      - name: Build AAB (bundleRelease)
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/upload.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew clean bundleRelease

      - name: Build APK (assembleRelease)
        env:
          KEYSTORE_PATH: upload.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew clean assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
